# Concise, factual antigen overviews (1-2 sentences each) keyed by antibody key.
OV = {
"CD3":"CD3 is the signal-transducing core of the T-cell receptor complex and the definitive pan–T-cell lineage marker, expressed on all αβ and γδ T cells. In spatial proteomics it is the anchor channel for identifying and segmenting the T-cell compartment.",
"CD4":"CD4 is a co-receptor defining helper T cells; it is also expressed at lower levels on monocytes, macrophages and some dendritic cells. Paired with CD3 it marks the T-helper lineage.",
"CD8":"CD8 (α-chain) defines cytotoxic T lymphocytes and is also found on a subset of NK and dendritic cells. It is a core channel for mapping anti-tumour and effector cytotoxicity.",
"CD5":"CD5 is a pan–T-cell marker also present on the B1 B-cell subset and in some B-cell lymphomas; useful for T-cell identification and lymphoma phenotyping.",
"CD2":"CD2 (LFA-2) is an adhesion/co-stimulatory receptor on T and NK cells that engages CD58, supporting immune-synapse biology in situ.",
"CD7":"CD7 is an early T/NK lineage antigen used to identify T and NK cells and, diagnostically, aberrant loss in T-cell neoplasms.",
"CD45RA":"CD45RA is the naive/effector isoform of the leukocyte common antigen, distinguishing naive and terminally-differentiated T cells from memory cells.",
"CD45RO":"CD45RO is the memory isoform of CD45, marking antigen-experienced memory T cells; paired with CD45RA it resolves naive-versus-memory states.",
"FoxP3":"FoxP3 is the master transcription factor of regulatory T cells (Tregs); its nuclear signal is the defining Treg channel for immunosuppression mapping.",
"CD25":"CD25 (IL-2 receptor α) marks activated and regulatory T cells and is a read-out of lymphocyte activation.",
"CD127":"CD127 (IL-7 receptor α) is high on conventional memory T cells and low on Tregs; CD25-high/CD127-low distinguishes Tregs.",
"T-bet":"T-bet (TBX21) is the master transcription factor driving Th1 and type-1 cytotoxic programs in T and NK cells.",
"GATA3":"GATA3 is the Th2 master transcription factor, also marking ILC2 and used diagnostically in breast and urothelial carcinoma.",
"CD278":"ICOS (CD278) is an inducible co-stimulator on activated and follicular-helper T cells, reporting T-cell activation.",
"CD185":"CXCR5 (CD185) directs follicular-helper T cells and B cells into B-cell follicles and germinal centres.",
"CXCR3":"CXCR3 is a chemokine receptor on Th1/effector T and NK cells that drives recruitment to inflamed tissue.",
"CCR4":"CCR4 is a chemokine receptor on Th2, skin-homing and regulatory T cells, and a target in cutaneous T-cell lymphoma.",
"KLRG1":"KLRG1 marks terminally-differentiated, senescent effector T and NK cells.",
"CD27":"CD27 is a co-stimulatory TNF-receptor on memory T cells and a subset of B cells, reporting differentiation state.",
"TCRgd":"The γδ T-cell receptor identifies the γδ T-cell subset, an unconventional lineage important at epithelial barriers.",
"TCRb":"The TCR β-chain identifies conventional αβ T cells, complementing CD3 for T-cell lineage resolution.",
"CD137":"4-1BB (CD137) is an inducible co-stimulatory receptor on recently-activated T and NK cells and an immunotherapy target.",
"OX40":"OX40 (CD134) is a co-stimulatory receptor on activated and regulatory T cells and an agonist-immunotherapy target.",
"CD154":"CD40L (CD154) on activated T cells licenses dendritic cells and B cells through CD40.",
"PD-1":"PD-1 (CD279) is the prototypic exhaustion/activation checkpoint on T cells; its spatial organisation predicts response to PD-1 blockade.",
"PD-L1":"PD-L1 (CD274) is the PD-1 ligand on tumour and myeloid cells; spatial PD-1/PD-L1 proximity is a key immuno-oncology read-out.",
"CD273":"PD-L2 (CD273) is a second PD-1 ligand on dendritic cells and macrophages.",
"CTLA4":"CTLA-4 (CD152) is a co-inhibitory checkpoint on regulatory and activated T cells and the target of ipilimumab-class drugs.",
"TIM3":"TIM-3 (HAVCR2) marks exhausted T cells and suppressive myeloid cells; a co-inhibitory checkpoint.",
"LAG3":"LAG-3 is a co-inhibitory checkpoint on exhausted T cells and an approved immunotherapy target.",
"VISTA":"VISTA (VSIR) is a myeloid-predominant negative checkpoint regulating T-cell activation.",
"CD276":"B7-H3 (CD276) is a checkpoint ligand over-expressed on tumour and myeloid cells and an emerging ADC/CAR target.",
"CD85j":"ILT2 (CD85j/LILRB1) is an inhibitory receptor on myeloid and NK cells that binds MHC-I and HLA-G.",
"CD19":"CD19 is a pan–B-cell co-receptor expressed from pro-B through plasmablast stages and the archetypal CAR-T target.",
"CD20":"CD20 (MS4A1) is a B-cell lineage marker (pre-B to memory B) and the target of rituximab-class therapy.",
"CD22":"CD22 is a B-cell inhibitory co-receptor used for B-cell identification and as an ADC target.",
"CD21":"CD21 (CR2) marks follicular dendritic cell networks and mature B cells, delineating germinal-centre architecture.",
"CD79a":"CD79a is a B-cell-receptor signalling subunit expressed throughout B-cell development including plasma cells.",
"CD79b":"CD79b is the partner BCR signalling subunit on B cells and an ADC target.",
"PAX5":"PAX5 is the B-lineage commitment transcription factor, nuclear and specific to B cells (lost in plasma cells).",
"Bcl6":"BCL-6 is the germinal-centre master transcription factor marking GC B cells and follicular-helper T cells.",
"IgD":"Surface IgD marks naive, pre-germinal-centre B cells.",
"IgM":"IgM is the first-expressed immunoglobulin, marking naive and some memory B cells.",
"IgG":"IgG marks class-switched memory B and plasma cells.",
"CD138":"CD138 (syndecan-1) is the definitive plasma-cell marker, also on some epithelium, and a myeloma target.",
"MUM1":"MUM-1/IRF4 marks plasma cells and activated B cells and is used in lymphoma classification.",
"BCMA":"BCMA (TNFRSF17) is a plasma-cell-restricted receptor and leading myeloma CAR-T/ADC target.",
"FcRH5":"FcRH5 is a B-/plasma-cell surface antigen and bispecific-antibody target.",
"Kappa":"Immunoglobulin κ light chain is used to assess B-/plasma-cell clonality (κ:λ restriction).",
"lambda":"Immunoglobulin λ light chain complements κ staining for clonality assessment.",
"CD56":"CD56 (NCAM1) marks NK cells and neuroendocrine/neural tissue; a core NK and neuroendocrine channel.",
"CD57":"CD57 marks mature/senescent NK cells and terminally-differentiated cytotoxic T cells.",
"CD16":"CD16 (FcγRIIIa) marks cytotoxic NK cells and mediates antibody-dependent cytotoxicity; also on neutrophils and macrophages.",
"NKG2D":"NKG2D (KLRK1) is an activating receptor on NK and cytotoxic T cells that senses stress-induced ligands.",
"NKp46":"NKp46 (NCR1) is a highly specific natural-cytotoxicity receptor marking NK cells.",
"KIR":"Killer-cell immunoglobulin-like receptors tune NK-cell self-tolerance via MHC-I recognition.",
"DNAM1":"DNAM-1 (CD226) is an activating adhesion receptor on NK and T cells engaging CD155/CD112.",
"CD94":"CD94 pairs with NKG2 receptors on NK and T cells to read HLA-E.",
"SlamF7":"SLAMF7 marks NK and plasma cells and is a myeloma immunotherapy target.",
"CD96":"CD96 (TACTILE) is an inhibitory NK/T-cell receptor competing with DNAM-1 for CD155.",
"CD68":"CD68 is a pan-macrophage/monocyte lysosomal marker, the standard channel for the mononuclear-phagocyte compartment.",
"CD163":"CD163 is a scavenger receptor marking M2-polarised, tissue-remodelling macrophages.",
"CD206":"CD206 (mannose receptor, MRC1) marks M2 macrophages and some dendritic cells.",
"arg-1":"Arginase-1 marks M2/immunosuppressive myeloid cells (and granulocytes); a hepatocyte marker in liver.",
"CD14":"CD14 marks monocytes/macrophages (and, in some tissues, a fibroblast subset); an LPS co-receptor.",
"CD11b":"CD11b (ITGAM) is a pan-myeloid integrin on macrophages, granulocytes and dendritic cells.",
"CD11c":"CD11c (ITGAX) marks dendritic cells and some macrophages; a core DC channel.",
"CD1c":"CD1c (BDCA-1) marks the cDC2 conventional dendritic-cell subset.",
"CD123":"CD123 (IL-3Rα) marks plasmacytoid dendritic cells and basophils and is a leukaemia-stem-cell target.",
"DC-lamp":"DC-LAMP (LAMP3) marks mature, antigen-presenting dendritic cells, often within lymphoid aggregates.",
"XCR1":"XCR1 specifically marks cross-presenting cDC1 dendritic cells.",
"IRF4":"IRF4 is a transcription factor marking cDC2, plasma cells and activated lymphocytes.",
"CD83":"CD83 marks activated/mature dendritic cells.",
"CD86":"CD86 (B7-2) is a co-stimulatory ligand on activated antigen-presenting cells.",
"CD40":"CD40 is a co-stimulatory TNF-receptor on dendritic cells, B cells and macrophages.",
"HLADR":"HLA-DR (MHC class II) marks professional antigen-presenting cells and activated T cells.",
"MHCI":"HLA-ABC (MHC class I) is expressed on all nucleated cells; its loss marks immune escape.",
"CD169":"CD169 (Siglec-1) marks sinusoidal/metallophilic macrophages in lymphoid organs.",
"CD36":"CD36 is a scavenger receptor on macrophages, endothelium and platelets, linked to lipid handling.",
"CD38":"CD38 is an activation ectoenzyme on plasma cells, NK and activated T cells; a myeloma target.",
"CD39":"CD39 (ENTPD1) marks regulatory T cells and suppressive myeloid cells in the adenosine axis.",
"CD73":"CD73 (NT5E) is an adenosine-generating ectoenzyme on fibroblasts, endothelium and Tregs; an IO target.",
"CD107":"CD107a (LAMP-1) marks degranulating cytotoxic lymphocytes, a functional cytotoxicity read-out.",
"MMR":"The macrophage mannose receptor (CD206/MRC1) marks M2 macrophages.",
"CD63":"CD63 is a tetraspanin marking activated mast cells and myeloid granules/exosomes.",
"IRF-8":"IRF8 is a transcription factor governing cDC1 and monocyte identity.",
"CD15":"CD15 marks neutrophils and eosinophils and Reed-Sternberg cells in Hodgkin lymphoma.",
"CD66":"CD66b (CEACAM8) is a granulocyte-activation marker on neutrophils and eosinophils.",
"MCT":"Mast-cell tryptase is the definitive mast-cell granule marker, robustly imaged in multiplexed panels.",
"CD117":"CD117/c-KIT marks mast cells, haematopoietic progenitors and GIST tumour cells.",
"panCK":"Pan-cytokeratin broadly marks epithelial and carcinoma cells, defining the epithelial compartment.",
"CK7":"Cytokeratin-7 marks glandular/ductal epithelium and is used in carcinoma-of-unknown-primary workups.",
"Keratin 8":"Cytokeratin-8 marks simple/luminal epithelium.",
"Ecad":"E-cadherin is the epithelial adherens-junction protein; its loss accompanies EMT.",
"p63":"p63 is a nuclear transcription factor marking basal/myoepithelial and squamous cells.",
"Sox2":"SOX2 marks basal/stem epithelial cells and is a squamous and CNS stem-cell factor.",
"MUC1":"MUC1/EMA marks glandular epithelium and is over-expressed on many carcinomas.",
"muc5ac":"MUC5AC marks mucinous/foveolar epithelium and airway/GI mucus.",
"CD49f":"CD49f (integrin α6) marks basal/stem epithelial cells.",
"CD104":"CD104 (integrin β4) marks basal epithelium at the hemidesmosome.",
"Nectin-4":"Nectin-4 is a carcinoma-associated adhesion molecule and the target of enfortumab vedotin.",
"PAX8":"PAX8 is a nuclear lineage marker for Müllerian, renal and thyroid epithelium.",
"Rab25":"Rab25 is an epithelial small GTPase linked to carcinoma aggressiveness.",
"SF-1":"Steroidogenic factor-1 (NR5A1) marks adrenocortical and gonadal-stromal cells.",
"Vimentin":"Vimentin is the mesenchymal intermediate filament marking fibroblasts, endothelium and many immune cells; an EMT marker.",
"SNAIL":"SNAIL (SNAI1) is an EMT-driving transcription factor repressing E-cadherin.",
"ZEB-1":"ZEB-1 is an EMT transcription factor in mesenchymal tumour and stromal cells.",
"cMyc":"c-Myc is a master proliferative/oncogenic transcription factor.",
"Bcat":"β-catenin is the Wnt-pathway effector at epithelial junctions; nuclear translocation marks Wnt activation.",
"HLA-G":"HLA-G is a non-classical MHC molecule mediating immune tolerance on trophoblast and immune-evasive tumours.",
"PDPN":"Podoplanin marks lymphatic endothelium, fibroblastic reticular cells and cancer-associated fibroblasts.",
"FAP":"Fibroblast activation protein marks cancer-associated fibroblasts and is a theranostic target.",
"PDGFRa":"PDGFRα marks fibroblasts and mesenchymal stroma.",
"PDGFR":"PDGFRβ marks pericytes and perivascular fibroblasts.",
"DDR2":"DDR2 is a collagen-sensing receptor on fibroblasts involved in matrix remodelling.",
"CD90":"CD90 (THY1) marks fibroblasts and mesenchymal stem/stromal cells.",
"Coll IV":"Collagen IV is the basement-membrane protein outlining epithelial and vascular boundaries.",
"CD31":"CD31 (PECAM1) is the pan-endothelial marker outlining blood (and lymphatic) vasculature.",
"CD34":"CD34 marks endothelium and haematopoietic/stromal progenitors.",
"VEGFR1":"VEGFR1 (FLT1) marks endothelium in angiogenic signalling.",
"VEGFR2":"VEGFR2 (KDR) is the principal pro-angiogenic VEGF receptor on endothelium.",
"MMP-9":"MMP-9 is a matrix-remodelling gelatinase from myeloid cells and stroma.",
"MMP12":"MMP-12 (macrophage elastase) marks tissue-remodelling macrophages.",
"GAS6":"GAS6 is a TAM-receptor ligand in efferocytosis and stromal signalling.",
"CD44":"CD44 is a hyaluronan receptor marking activated and stem-like cells.",
"CD54":"ICAM-1 (CD54) is an adhesion molecule upregulated on activated endothelium and APCs.",
"L1CAM":"L1CAM is a neural adhesion molecule marking neurons and aggressive neural/epithelial tumours.",
"Ki67":"Ki-67 (MKI67) is the universal proliferation marker, nuclear in cycling cells of any lineage.",
"PCNA":"PCNA marks proliferating cells through its role in DNA replication.",
"PARP1":"PARP-1 is a DNA-damage-response enzyme and a target of PARP inhibitors.",
"MRE11":"MRE11 is a DNA double-strand-break repair sensor.",
"SLFN11":"SLFN11 predicts sensitivity to DNA-damaging therapy.",
"ARID1A":"ARID1A is a SWI/SNF chromatin-remodeller frequently mutated in cancer.",
"p16":"p16 (INK4a) marks senescence and HPV-driven tumours.",
"FoxO1":"FoxO1 is a stress-responsive transcription factor.",
"pstat3":"Phospho-STAT3 reports active IL-6/JAK–STAT signalling and is detectable in multiplexed imaging.",
"HIF1a":"HIF-1α is the master hypoxia transcription factor stabilised in low-oxygen niches.",
"HIF2a":"HIF-2α (EPAS1) is a hypoxia transcription factor prominent in endothelium and renal tumours.",
"TGFb":"TGF-β is an immunosuppressive, pro-fibrotic cytokine shaping the stromal niche.",
"IFNg":"IFN-γ is the signature type-1 effector cytokine from Th1, NK and CD8 cells.",
"CXCL10":"CXCL10 is an IFN-induced chemokine recruiting CXCR3+ effector cells.",
"CD69":"CD69 is an early-activation and tissue-residency marker on lymphocytes.",
"CD71":"CD71 (transferrin receptor) marks proliferating and erythroid cells.",
"CD235a":"CD235a (glycophorin A) is the erythrocyte/erythroid-lineage marker.",
"MICA/B":"MICA/B are stress-induced NKG2D ligands on tumour/epithelial cells.",
"CD155":"CD155 (PVR) is a checkpoint ligand for TIGIT/CD226 on tumour and myeloid cells.",
"CD9":"CD9 is a tetraspanin on platelets, epithelium and exosomes.",
"CD30":"CD30 marks activated T/B cells and Reed-Sternberg cells; the target of brentuximab vedotin.",
}
